"""Occult System contracts and feature-gated integration helpers.

The package is deliberately inert. Importing it does not register providers,
change prompts, or alter Hermes runtime behavior.
"""

from agent.occult.contracts import (
    OCCULT_CONTRACT_VERSION,
    SUPPORTED_CAPABILITIES,
    ContractVersionMismatch,
    InvalidContractPayload,
    OccultContractError,
    UnsupportedCapability,
    contract_json_schema,
    is_occult_enabled,
    load_contract_fixture,
    load_contract_schema,
    validate_event_stream,
    validate_invocation,
)
from agent.occult.credential_broker import (
    CredentialBoundaryError,
    CredentialReference,
    CredentialStatus,
    InMemoryCredentialBroker,
    SecretValue,
)
from agent.occult.mythos import (
    AcquisitionAction,
    AdapterRequest,
    AdapterResponse,
    FailureKind,
    MinorArcanaDescriptor,
    MythosError,
    MythosRouter,
    MythosRoutingError,
    MythosStateStore,
    NoEligibleRoute,
    PrivacyClass,
    ProviderFailure,
    ProviderTrustState,
    QuotaPoolState,
    RouteRegistrationError,
    RouteResult,
    descriptor_from_provider,
    enforce_acquisition_policy,
)

__all__ = [
    "OCCULT_CONTRACT_VERSION",
    "SUPPORTED_CAPABILITIES",
    "AcquisitionAction",
    "AdapterRequest",
    "AdapterResponse",
    "ContractVersionMismatch",
    "CredentialBoundaryError",
    "CredentialReference",
    "CredentialStatus",
    "FailureKind",
    "InMemoryCredentialBroker",
    "InvalidContractPayload",
    "MinorArcanaDescriptor",
    "MythosError",
    "MythosRouter",
    "MythosRoutingError",
    "MythosStateStore",
    "NoEligibleRoute",
    "OccultContractError",
    "PrivacyClass",
    "ProviderFailure",
    "ProviderTrustState",
    "QuotaPoolState",
    "RouteRegistrationError",
    "RouteResult",
    "SecretValue",
    "UnsupportedCapability",
    "contract_json_schema",
    "descriptor_from_provider",
    "enforce_acquisition_policy",
    "is_occult_enabled",
    "load_contract_fixture",
    "load_contract_schema",
    "validate_event_stream",
    "validate_invocation",
]
