"""Occult System contracts and feature-gated integration helpers.

The package is deliberately inert. Importing it does not register providers,
change prompts, or alter Hermes runtime behavior.
"""

from agent.occult.contracts import (
    OCCULT_CONTRACT_VERSION,
    SUPPORTED_CAPABILITIES,
    ContractVersionMismatch,
    InvalidContractPayload,
    OccultContractError,
    UnsupportedCapability,
    contract_json_schema,
    is_occult_enabled,
    load_contract_fixture,
    load_contract_schema,
    validate_event_stream,
    validate_invocation,
)
from agent.occult.credential_broker import (
    CredentialBoundaryError,
    CredentialReference,
    CredentialStatus,
    InMemoryCredentialBroker,
    SecretValue,
)
from agent.occult.mythos import (
    AcquisitionAction,
    AdapterRequest,
    AdapterResponse,
    FailureKind,
    MinorArcanaDescriptor,
    MythosError,
    MythosRouter,
    MythosRoutingError,
    MythosStateStore,
    NoEligibleRoute,
    PrivacyClass,
    ProviderFailure,
    ProviderTrustState,
    QuotaPoolState,
    RouteRegistrationError,
    RouteResult,
    descriptor_from_provider,
    enforce_acquisition_policy,
)
from agent.occult.pairing import (
    MemoryRecord,
    PairingContext,
    PairingError,
    PairingSession,
    RuntimePolicy,
    ToolAuthorization,
    ToolAuthorizationDecision,
)
from agent.occult.http import OccultHTTPAdapter
from agent.occult.readings import (
    CouncilNodeRequest,
    CouncilNodeResult,
    ReadingError,
    ReadingNode,
    ReadingPlan,
    ReadingStore,
)
from agent.occult.tarot_packages import (
    InstalledTarotPackage,
    SystemPackagePolicy,
    TarotManifest,
    TarotPackageError,
    TarotPackageManager,
    ValidatedTarotPackage,
)
from agent.occult.service import OccultService
from agent.occult.virtual_tokens import (
    SQLiteVirtualTokenStore,
    VirtualTokenAuthority,
    VirtualTokenError,
    VirtualTokenLease,
    VirtualTokenPolicy,
)

__all__ = [
    "OCCULT_CONTRACT_VERSION",
    "SUPPORTED_CAPABILITIES",
    "AcquisitionAction",
    "AdapterRequest",
    "AdapterResponse",
    "ContractVersionMismatch",
    "CouncilNodeRequest",
    "CouncilNodeResult",
    "CredentialBoundaryError",
    "CredentialReference",
    "CredentialStatus",
    "FailureKind",
    "InMemoryCredentialBroker",
    "InvalidContractPayload",
    "MinorArcanaDescriptor",
    "MemoryRecord",
    "MythosError",
    "MythosRouter",
    "MythosRoutingError",
    "MythosStateStore",
    "NoEligibleRoute",
    "OccultContractError",
    "OccultHTTPAdapter",
    "OccultService",
    "PairingContext",
    "PairingError",
    "PairingSession",
    "PrivacyClass",
    "ProviderFailure",
    "ProviderTrustState",
    "QuotaPoolState",
    "ReadingError",
    "ReadingNode",
    "ReadingPlan",
    "ReadingStore",
    "RouteRegistrationError",
    "RouteResult",
    "RuntimePolicy",
    "SecretValue",
    "SQLiteVirtualTokenStore",
    "SystemPackagePolicy",
    "TarotManifest",
    "TarotPackageError",
    "TarotPackageManager",
    "ToolAuthorization",
    "ToolAuthorizationDecision",
    "UnsupportedCapability",
    "contract_json_schema",
    "descriptor_from_provider",
    "enforce_acquisition_policy",
    "is_occult_enabled",
    "load_contract_fixture",
    "load_contract_schema",
    "validate_event_stream",
    "validate_invocation",
    "ValidatedTarotPackage",
    "VirtualTokenAuthority",
    "VirtualTokenError",
    "VirtualTokenLease",
    "VirtualTokenPolicy",
    "InstalledTarotPackage",
]
